SET FOREIGN_KEY_CHECKS=0;
INSERT INTO tbl_topic (topic_id, topic_name, parent_topic_id) values('1','Java',null);
INSERT INTO tbl_topic (topic_id, topic_name, parent_topic_id) values('2','C',null);
INSERT INTO tbl_topic (topic_id, topic_name, parent_topic_id) values('3','C++',null);
INSERT INTO tbl_topic (topic_id, topic_name, parent_topic_id) values('4','Collection','1');
INSERT INTO tbl_topic (topic_id, topic_name, parent_topic_id) values('5','Multithreading','1');
INSERT INTO tbl_topic (topic_id, topic_name, parent_topic_id) values('6','OOPS','1');
INSERT INTO tbl_topic (topic_id, topic_name, parent_topic_id) values('7','OOPS','3');
INSERT INTO tbl_topic (topic_id, topic_name, parent_topic_id) values('8','Executor Framework','5');
INSERT INTO tbl_topic (topic_id, topic_name, parent_topic_id) values('9','Future','8');
INSERT INTO tbl_topic (topic_id, topic_name, parent_topic_id) values('10','Core Java',null);
INSERT INTO tbl_topic (topic_id, topic_name, parent_topic_id) values('11','Algorithm',null);
INSERT INTO tbl_topic (topic_id, topic_name, parent_topic_id) values('12','JSP',null);
INSERT INTO tbl_topic (topic_id, topic_name, parent_topic_id) values('13','JPA',null);
INSERT INTO tbl_topic (topic_id, topic_name, parent_topic_id) values('14','Pointer','2');
INSERT INTO tbl_topic (topic_id, topic_name, parent_topic_id) values('15','Generics','4');

INSERT INTO tbl_topic_linking (topic_id, linked_topic_id) values('1','4');
INSERT INTO tbl_topic_linking (topic_id, linked_topic_id) values('1','5');
INSERT INTO tbl_topic_linking (topic_id, linked_topic_id) values('1','6');
INSERT INTO tbl_topic_linking (topic_id, linked_topic_id) values('2','0');
INSERT INTO tbl_topic_linking (topic_id, linked_topic_id) values('3','4');
INSERT INTO tbl_topic_linking (topic_id, linked_topic_id) values('3','7');
SET FOREIGN_KEY_CHECKS=1;